
###### test eval
6765

###### test throw
exception catched
some string

###### test Value.is_xxx
instanceof | pass
convert_to_string | pass
null | pass
undefined | pass
true | pass
1 | pass
"string" | pass
Symbol() | pass
[] | pass
({obj:true}) | pass
parseInt | pass
String | pass
new Error() | pass
1n | pass

###### test Value.to_xxx
true
10
9007199254740991
1
0.30000000000000004

###### test bytecode
6765

###### test interrupt_handler
run once
InternalError: interrupted
